name: Docker OpenVPN Client

on:
  workflow_dispatch:
  repository_dispatch:
    types: [debian-updated]

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/openvpn-client:latest
      -
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.BUILD_INTEGRATION }}
          repository: fernandoenzo/docker-openvpn-server
          event-type: openvpn-client-updated
